"""Minor Arcana seed data (56 cards) for Mystic XP.
Structure mirrors Major Arcana entries in server.py.
"""

SUIT_META = {
    "Wands":    {"element": "Fire",  "emoji": "🔥", "file": "Wands"},
    "Cups":     {"element": "Water", "emoji": "🍷", "file": "Cups"},
    "Swords":   {"element": "Air",   "emoji": "⚔️", "file": "Swords"},
    "Pentacles":{"element": "Earth", "emoji": "🪙", "file": "Pents"},
}

COURT_NAMES = {11: "Page", 12: "Knight", 13: "Queen", 14: "King"}


# Data per card: (num, name, kw_up, kw_rev, upright, reversed, description, symbolism)
# Numbers: 1=Ace, 2-10 pip, 11=Page, 12=Knight, 13=Queen, 14=King
_WANDS = [
    (1, "Ace of Wands",
        ["inspiration", "new spark", "creative ignition", "passion", "potential"],
        ["delays", "creative block", "lack of direction", "hesitation", "false start"],
        "The Ace of Wands is the first spark of a new passion — an idea, project, or desire that suddenly burns bright. Act on the inspiration while it's fresh; hesitation smothers the flame.",
        "Reversed, the spark sputters. You may have inspiration without the follow-through, or fear of your own fire keeps it hidden. Wait, or fan the ember gently.",
        "A hand emerging from a cloud grasps a sprouting wand, leaves falling like drops. A castle sits atop a distant hill.",
        "The sprouting wand is raw creative life force; the falling leaves are the ten sephirot of the Tree of Life. The distant castle is what your inspiration could build."),
    (2, "Two of Wands",
        ["planning", "choice of paths", "future vision", "personal power", "discovery"],
        ["fear of the unknown", "playing safe", "indecision", "restricted view", "lack of planning"],
        "Two of Wands finds you at a decision point — the world in your hand, choices ahead. You've built something real; now consider expansion, travel, a bigger stage.",
        "Reversed, fear keeps you inside familiar walls. Overplanning or an inability to leave the current comfort blocks the larger vision.",
        "A figure in a red robe stands on a castle rampart holding a globe, gazing at the sea. One wand is fixed to the wall; the other is held in hand.",
        "The globe is dominion already achieved; the fixed wand is what's secured; the held wand is future potential — you choose whether to plant it elsewhere."),
    (3, "Three of Wands",
        ["expansion", "foresight", "long-term vision", "leadership", "exploration"],
        ["delays", "obstacles", "lack of foresight", "setbacks abroad", "playing small"],
        "Three of Wands rewards early effort — ships you sent out begin returning. Look ahead, expand your horizons, welcome opportunities from further afield.",
        "Reversed, ventures stall or return empty. Delays, missed timing, or your ambitions were too narrow to reach far.",
        "A cloaked figure stands on a cliff overlooking the sea, watching ships in the distance. Three wands are planted in the ground around him.",
        "The sea is the world of larger possibility; the ships are ventures already launched. The three wands anchor the seeker in a stable, watchful stance."),
    (4, "Four of Wands",
        ["celebration", "harmony", "home", "milestone", "community"],
        ["transition", "instability at home", "cancelled celebration", "tension in family", "delay of joy"],
        "Four of Wands marks a genuine, hard-earned celebration — a wedding, homecoming, or milestone worth honoring publicly. Gather your people; joy shared is joy multiplied.",
        "Reversed, the celebration is delayed or the foundation feels shaky. Tensions at home or a passage that hasn't yet found its ceremony.",
        "Two figures dance with bouquets under a garland-draped canopy formed by four wands. A castle stands behind them; villagers gather.",
        "The four wands form a chuppah — a sacred canopy of arrival. The garlands celebrate abundance; the castle in the background signifies stability earned."),
    (5, "Five of Wands",
        ["conflict", "competition", "disagreement", "friction", "sparring"],
        ["resolution", "avoiding conflict", "inner tension", "release", "cooperation"],
        "Five of Wands is the friction of many voices, competing ideas, or petty rivalries. It's rarely serious — more the noisy jostling of ego. Engage constructively or step out of the ring.",
        "Reversed, conflict resolves or turns inward. Peace returns, or the argument you're avoiding festers privately.",
        "Five youths clash their wands in what may be play or fight, hard to tell. Each figure wears different colored clothing.",
        "The varied garb signals different perspectives without common cause. The ambiguous action — play or violence — is the essence of unnecessary friction."),
    (6, "Six of Wands",
        ["victory", "recognition", "public acclaim", "success", "confidence"],
        ["private win", "delayed recognition", "arrogance", "fall from favor", "ego"],
        "Six of Wands is victory acknowledged — you've won, and others see it. Ride the parade, but keep the horse's reins short; the crowd's love is generous but fickle.",
        "Reversed, the applause is missing or the win private. Alternatively, ego has outrun the achievement, or public favor turns.",
        "A crowned rider on a white horse holds a laurel-wreathed wand aloft. Foot soldiers march alongside, one holding another wand.",
        "The laurel wreath is classical victory; the white horse, purity of the triumph. The soldiers walking alongside show that success has followers — always more than one is required."),
    (7, "Seven of Wands",
        ["standing your ground", "defense", "conviction", "challenge", "perseverance"],
        ["overwhelm", "yielding", "self-doubt", "giving up", "backing down"],
        "Seven of Wands puts you on the high ground with challengers coming up from below. You have the position — hold it. Your convictions are worth defending even against many.",
        "Reversed, the pressure exhausts you or your position wasn't as secure as you thought. Consider whether the fight is worth it.",
        "A man in mismatched shoes stands on a hilltop, brandishing his wand against six wands pointing up at him from below.",
        "The mismatched shoes suggest hasty preparation — real defenses are often improvised. Being on high ground means the seeker's position is naturally stronger, but only if held."),
    (8, "Eight of Wands",
        ["swift action", "movement", "messages", "momentum", "clarity"],
        ["delays", "frustration", "scattered energy", "miscommunication", "resistance"],
        "Eight of Wands is arrows in flight — messages, decisions, and events moving fast. Ride the momentum. Answer quickly; the window closes.",
        "Reversed, everything stalls. Miscommunication, missed messages, or scattered energy fragments what should have moved together.",
        "Eight wands fly through the air across a clear sky above green countryside and a river — no human figures.",
        "The absence of people is the point: this energy moves under its own steam. The parallel trajectory shows aligned intention; the flight over water suggests emotion and message combined."),
    (9, "Nine of Wands",
        ["resilience", "boundaries", "last stand", "grit", "wary strength"],
        ["exhaustion", "paranoia", "burnout", "walls too high", "refusal of help"],
        "Nine of Wands is the wounded warrior standing one more time. You're battle-weary but not broken; the finish is closer than it looks. Guard, but don't isolate.",
        "Reversed, exhaustion has crossed into paranoia. Walls meant to protect now imprison. Rest is not surrender.",
        "A bandaged man leans on a wand, looking wearily to the side. Eight wands stand behind him like a fence.",
        "The bandage is honest — this figure has been hurt and shows it. The wand-fence is boundary work: hard-won knowledge of where to hold the line. His side-glance shows watchfulness, not fear."),
    (10, "Ten of Wands",
        ["burden", "responsibility", "overload", "commitment", "grind"],
        ["release", "delegation", "letting go", "collapse", "collapse of burden"],
        "Ten of Wands is carrying too much toward a goal that is nearly reached. You've committed to more than one back can bear. Finish, then set some down permanently.",
        "Reversed, the load is dropped — by choice or collapse. Relief, or the collapse itself was necessary to force sharing the weight.",
        "A stooped figure trudges toward a distant town, arms wrapped around ten wands blocking his view of the path.",
        "The wands block sight — over-commitment means you can't see where you're going. The town is achievable but the seeker has taken responsibility for too much of the load. Delegation is the missing lesson."),
    (11, "Page of Wands",
        ["curiosity", "eager beginner", "adventure", "spark of ideas", "youthful energy"],
        ["impatience", "immaturity", "false starts", "restlessness", "scattered enthusiasm"],
        "Page of Wands is a message-bearer of new inspiration — often a young person or a young idea. Curiosity outruns experience, and that's the gift. Follow the thread wherever it leads first.",
        "Reversed, the spark scatters into a dozen abandoned starts. Impatience with slow growth; a promise made without follow-through.",
        "A youthful figure in colorful robes stands in a desert, gazing up at his wand as if it might sprout leaves at any moment. Salamanders decorate his tunic.",
        "The salamanders are alchemical fire spirits — pure passion. The desert setting shows raw potential without yet a landscape. The gaze upward is expectation, not entitlement."),
    (12, "Knight of Wands",
        ["boldness", "action", "adventure", "impulsive drive", "charisma"],
        ["recklessness", "burnout", "arrogance", "unfinished projects", "aggression"],
        "Knight of Wands charges — fast horse, brighter idea, no map. Drawing this card affirms bold action pays now; hesitation costs more than the mistake would have. Ride, but glance at the horizon.",
        "Reversed, the charge becomes reckless. Projects abandoned mid-gallop, tempers hot, promises to people you left in the dust.",
        "An armored knight rides a rearing horse, holding a leafy wand aloft. Salamanders and yellow flames decorate his tunic and cape.",
        "The rearing horse is the moment of decision to charge — kinetic potential. Salamanders again mark fire spirits; the leafy wand shows this action is still creative, not destructive."),
    (13, "Queen of Wands",
        ["confidence", "warmth", "magnetism", "creative leadership", "vibrancy"],
        ["insecurity", "jealousy", "burnout", "domineering warmth turned demanding", "hidden self-doubt"],
        "Queen of Wands radiates — she brings warmth to any room, leads without needing to prove it, and knows her own worth without checking. Embody this energy: be seen, be yourself, welcome others into your light.",
        "Reversed, the flame becomes needy or scorching. Jealousy, insecurity behind bravado, or warmth that has demands attached.",
        "A crowned queen sits on a stone throne carved with lions and sunflowers, holding a leafy wand in one hand and a sunflower in the other. A black cat sits at her feet.",
        "Sunflowers turn toward the sun — she is a source others orient to. Lions on the throne mark royal fire; the black cat signals independent, intuitive shadow work behind the public brightness."),
    (14, "King of Wands",
        ["vision", "leadership", "entrepreneur", "bold direction", "seasoned fire"],
        ["autocracy", "impulsiveness at scale", "impatience", "arrogance", "burnout of leadership"],
        "King of Wands leads by clear vision. He's not the noisiest voice, but the room follows him because he's already three steps down the road. Set direction; trust others to walk it with you.",
        "Reversed, vision turns to autocracy. Impatience with those who need explanations, impulsive decisions at scale, or the crown weighs and no one is trusted enough to help.",
        "A crowned king sits on a throne bearing salamanders and lions, holding a flowering wand. His robe is embroidered with fire symbols.",
        "The flowering wand shows his fire is generative, not destructive — he creates enterprises, movements, families. The salamander-lion combination unites primal instinct (lion) with alchemical spirit (salamander): mastery of both raw and refined power."),
]

_CUPS = [
    (1, "Ace of Cups",
        ["new love", "emotional beginning", "compassion", "spiritual opening", "receptivity"],
        ["blocked emotions", "self-love needed", "empty cup", "delayed feelings", "guardedness"],
        "Ace of Cups is the heart's opening — new love, creative flow, or spiritual grace pouring in. Receive without asking whether you deserve it. The cup is offered.",
        "Reversed, the cup tips or is set down. Emotions blocked, love withheld from self, or a feeling you can't yet let in.",
        "A hand extends from a cloud holding a chalice overflowing with five streams. A dove descends into the cup carrying a wafer marked with a cross.",
        "The five streams are the five senses now flooded with feeling; the dove is the Holy Spirit descending into the vessel of the heart. The cup does not merely fill — it overflows, signifying grace exceeds capacity."),
    (2, "Two of Cups",
        ["partnership", "connection", "mutual attraction", "equality", "recognition"],
        ["imbalance", "miscommunication", "broken bond", "one-sided love", "disconnection"],
        "Two of Cups is genuine partnership — two beings who see each other clearly and choose union. Romance, friendship, or business alliance built on real recognition. Say yes.",
        "Reversed, imbalance enters the bond. Miscommunication, one giving more than the other, or a connection quietly disconnecting.",
        "A man and woman face each other, each holding a cup, and lift them in a toast. Above them floats a caduceus with a lion's head — the Cadaceus of Hermes crowned by leonine passion.",
        "The exchanged cups signal that each brings something to the other. The lion-crowned caduceus is love that heals — passion (lion) guided by wisdom (Hermes' staff)."),
    (3, "Three of Cups",
        ["celebration", "friendship", "community", "joy", "shared success"],
        ["overindulgence", "gossip", "third-party issues", "isolation", "shallow connection"],
        "Three of Cups is the joy of chosen company — friends celebrating a milestone, a community that gets you. Drink to the good. Give thanks aloud.",
        "Reversed, the party turns hollow. Overindulgence, gossip, a third party disturbing a pair, or you're outside a circle you used to be part of.",
        "Three women in flowing robes lift golden cups in a joyful dance amid an abundant harvest of fruit at their feet.",
        "Three is the number of shared joy — a duo becomes community only when a third witnesses. The harvest at their feet is fruit already ripened; celebration marks the acknowledgment of what has already grown."),
    (4, "Four of Cups",
        ["apathy", "contemplation", "reevaluation", "disinterest", "meditation"],
        ["new awareness", "acceptance", "moving on", "renewed motivation", "opportunity noticed"],
        "Four of Cups shows you sitting under a tree, ignoring a fourth cup an unseen hand offers. Contentment has curdled into apathy; something available is being overlooked.",
        "Reversed, awareness returns. What was missed becomes visible; motivation stirs again.",
        "A young man sits with arms folded beneath a tree, gazing at three cups in front of him while a hand from a cloud offers him a fourth.",
        "The three cups on the ground are what he already has and no longer values. The cloud-offered fourth cup is grace unseen; his folded arms are the closed heart posture — help arrives but is not received."),
    (5, "Five of Cups",
        ["grief", "regret", "loss", "focus on failure", "disappointment"],
        ["acceptance", "healing", "moving forward", "recovered hope", "forgiveness"],
        "Five of Cups is grief for what was spilled — real loss, honestly felt. But two cups behind you still stand. Don't rush the sorrow; also don't let it hide what remains.",
        "Reversed, the head lifts. What is still standing is finally seen; forgiveness of self or other becomes possible.",
        "A cloaked figure looks down at three spilled cups on the ground. Behind him, unnoticed, stand two upright cups. A river flows nearby toward a bridge and a distant house.",
        "The three spilled cups are what was lost; the two upright are what remains and is easy to miss when grief owns the gaze. The bridge and house across the river are the return home — always available when the mourner is ready."),
    (6, "Six of Cups",
        ["nostalgia", "childhood", "innocent joy", "old friends", "reunion"],
        ["stuck in the past", "unresolved childhood", "moving on", "outgrown ties", "romanticizing"],
        "Six of Cups is a bath in sweet memory — reconnection with someone from before, a return to an older self, a moment of innocent joy. Let it soften you.",
        "Reversed, nostalgia turns into a trap. Refusing to grow up, romanticizing a past that wasn't as safe as it felt, or clinging to people who fit an older version of you.",
        "A tall child hands a cup filled with white flowers to a small child in an old courtyard. Four other flower-filled cups rest around them; a fifth stands nearby.",
        "The exchange of flower-cups is generosity between the past and the present. The courtyard is a childhood home space — safe, small, and time-suspended."),
    (7, "Seven of Cups",
        ["choices", "fantasy", "possibilities", "illusion", "temptation"],
        ["clarity", "focus", "reality check", "sorting priorities", "commitment"],
        "Seven of Cups floats many shiny possibilities before you — some real, some fantasy. The excitement is in the choosing; the discipline is in choosing only what actually exists.",
        "Reversed, the fog clears. You commit to one thing and let the mirages evaporate. Priorities snap into focus.",
        "A silhouetted figure gazes at seven cups floating in a cloud, each containing a different vision: a face, a snake, a castle, jewels, a laurel wreath, a dragon, and a shrouded figure.",
        "The cups float in cloud — the realm of possibility unanchored to earth. Some contents (jewels, wreath) are seductive; others (snake, dragon) are warnings; the shrouded figure is the unknown self that shows up in every real choice."),
    (8, "Eight of Cups",
        ["walking away", "quest for meaning", "abandonment of the false", "leaving comfort", "seeking"],
        ["fear of change", "stagnation", "returning", "clinging to the old", "avoidance of departure"],
        "Eight of Cups is the moment you leave the good-enough behind. Nothing catastrophic — just that you've outgrown it, and staying would be a lie. Walk into the unknown; the moon lights the path.",
        "Reversed, you turn back or refuse to leave. Comfort holds you where meaning cannot follow.",
        "A cloaked figure walks away from eight stacked cups toward mountains under a moon that shows both eclipsed and full faces.",
        "The stacked cups look complete — but one cup's worth of space at the top is empty: the seeker sensed the missing piece and left rather than pretend. The double-faced moon is the intersection of waxing and waning: this is a threshold, not a rejection."),
    (9, "Nine of Cups",
        ["contentment", "wish fulfilled", "satisfaction", "gratitude", "abundance"],
        ["superficial success", "smugness", "unfulfilled wish", "materialism", "hollow abundance"],
        "Nine of Cups is the 'wish card' — deep satisfaction, a desire granted, well-earned pleasure. Enjoy openly. Just don't confuse comfort for the whole life.",
        "Reversed, satisfaction rings hollow. The wish granted wasn't the real one, or smugness cools generosity into self-congratulation.",
        "A well-fed man sits on a bench with arms folded, smiling contentedly. Behind him, nine golden cups are arranged on a shelf like trophies.",
        "The nine cups on display are enough — abundance is complete. His folded arms show contentment tipping toward self-satisfaction; the bench is broad enough for others, but he sits alone."),
    (10, "Ten of Cups",
        ["family joy", "harmony", "emotional fulfillment", "belonging", "true home"],
        ["broken family", "disconnection", "unmet expectations", "domestic strife", "false harmony"],
        "Ten of Cups is emotional completion — a home you belong to, people who see you, love as landscape rather than event. Not perfection, but the real thing.",
        "Reversed, the family portrait cracks. Expectations mismatched with reality, tension beneath the surface, or a home that never felt like one.",
        "A couple stands with arms around each other, gesturing toward a rainbow of ten cups arching over their home. Two children dance nearby.",
        "The rainbow of cups is emotional completion visible in the sky — abundance blessed. The dancing children signify joy passed to the next generation; the home in the landscape shows love embedded in place."),
    (11, "Page of Cups",
        ["intuitive message", "creative sensitivity", "new feelings", "curiosity of the heart", "gentle wonder"],
        ["moodiness", "emotional immaturity", "creative block", "escapism", "hidden feelings"],
        "Page of Cups brings a tender message — a poem, a dream, a shy love, an intuition too soft to explain. Listen. Something delicate is trying to arrive.",
        "Reversed, the tender message is refused or the messenger sulks. Moodiness, emotional immaturity, or an intuition dismissed for being too subtle to prove.",
        "A youthful figure in a blue tunic decorated with lotus flowers stands by the sea, holding a golden cup from which a small fish curiously emerges.",
        "The fish from the cup is intuition surfacing — a message from the depths made visible. The lotus flowers are spiritual awakening emerging through emotion. The sea in the background is the vast unconscious the Page is just beginning to fish."),
    (12, "Knight of Cups",
        ["romance", "offer of love", "artistic quest", "grace", "chivalry"],
        ["moodiness", "deceptive charm", "unrealistic proposals", "withdrawn romance", "emotional inconsistency"],
        "Knight of Cups arrives with a proposal — of love, of art, of an emotional journey. He is graceful, poetic, sincere in the moment. Say yes to the offering if it moves you.",
        "Reversed, romance without follow-through. Charm concealing avoidance, poetic promises with no ground beneath them, or a lover who withdraws when feelings become real.",
        "A knight in a winged helmet rides a slow-walking white horse, offering a cup forward. His armor is decorated with fish symbols.",
        "The winged helmet is imagination and idealism; the slow walk shows this knight moves at the pace of feeling, not urgency. The fish on his armor mark him as a messenger between the surface world and the depths of emotion."),
    (13, "Queen of Cups",
        ["compassion", "empathy", "intuition", "emotional depth", "healing presence"],
        ["overwhelm", "emotional flooding", "codependence", "martyrdom", "leaky boundaries"],
        "Queen of Cups feels everything — and holds it with grace. She listens without fixing, loves without demanding, and heals by presence alone. Embody or receive this depth.",
        "Reversed, the queen drowns. Empathy without boundaries becomes codependence; martyrdom masquerades as love; feelings flood the vessel.",
        "A crowned queen sits on a stone throne at the water's edge, holding an ornate covered cup with handles like angels. Waves lap at her feet; scallop shells and sea creatures adorn the throne.",
        "Her closed cup is the only one in the deck — she alone holds what cannot be poured out casually. The water at her feet is the emotional realm; she rules by living at the edge rather than in the depths. The scallop and creatures show her connection to the ocean of feeling."),
    (14, "King of Cups",
        ["emotional mastery", "compassionate leadership", "calm authority", "diplomacy", "wise counsel"],
        ["moodiness suppressed", "manipulation", "emotional coldness", "hidden turmoil", "over-control of feelings"],
        "King of Cups rules the sea by staying above it — his throne floats on stormy water, but he is calm. Emotional mastery isn't lack of feeling; it's leadership through it. Be this presence for others.",
        "Reversed, calm becomes suppression. Cold detachment, manipulation dressed as diplomacy, or a churn beneath the still surface that leaks in disguised ways.",
        "A crowned king sits on a stone throne floating on a turbulent sea, holding a cup in one hand and a scepter in the other. A ship sails behind him; a fish leaps from the water beside him.",
        "The floating throne on rough water is his defining feat — mastery of the emotional realm without being consumed by it. The ship shows enterprise steady through storm; the leaping fish is intuition available to him even at rest."),
]

_SWORDS = [
    (1, "Ace of Swords",
        ["clarity", "breakthrough", "truth", "mental power", "decisive insight"],
        ["confusion", "misinformation", "clouded judgement", "brutal truth", "poor communication"],
        "Ace of Swords is the sword of truth appearing from cloud — sudden clarity that cuts through confusion. Speak plainly, decide sharply, and honor the insight while it's clean.",
        "Reversed, the blade blunts. Misinformation, foggy thinking, or truth wielded cruelly rather than surgically.",
        "A hand from a cloud grasps an upright sword crowned with a laurel wreath, points of light falling around it.",
        "The wreath crown is victory of intellect over confusion. The falling Yod-like sparks are divine sparks accompanying a truth breakthrough. The sword pointed up marks decisive alignment with sky (mind), not earth."),
    (2, "Two of Swords",
        ["stalemate", "difficult choice", "avoidance", "balance", "closed eyes"],
        ["indecision paralysis", "information revealed", "release of avoidance", "confusion", "seeing the truth"],
        "Two of Swords sits blindfolded before crossed blades — refusing to choose because either path costs something. Stalemate is a decision too. Take off the blindfold.",
        "Reversed, the truth surfaces. What was avoided becomes unavoidable; movement returns, sometimes painfully.",
        "A blindfolded woman sits on a stone bench holding two crossed swords over her heart. A crescent moon hangs above; still water and rocky islands are behind her.",
        "The blindfold is willed unknowing; the crossed blades are the two options she refuses to weigh. The moon is intuition present but ignored; the still water hides depth beneath a placid decision-refusing surface."),
    (3, "Three of Swords",
        ["heartbreak", "grief", "painful truth", "sorrow", "betrayal"],
        ["healing", "forgiveness", "releasing pain", "moving through grief", "unresolved sorrow"],
        "Three of Swords is heartbreak — clean and honest. Someone or something has pierced you, and denial won't seal the wound. Let it hurt where it must; the sky is already opening.",
        "Reversed, healing begins or grief overstays. The three blades pull free, or you clutch them long past their teaching.",
        "A red heart is pierced by three swords against a background of dark clouds and heavy rain.",
        "The heart is shown directly — no figure, no context. Grief is often uncontexted, universal. The three blades enter cleanly (not shattering) — this is a piercing you will survive. The rain outside the heart is the atmosphere of mourning."),
    (4, "Four of Swords",
        ["rest", "recovery", "retreat", "meditation", "convalescence"],
        ["restlessness", "burnout ignored", "premature return", "stagnation", "avoiding recovery"],
        "Four of Swords is enforced rest — the body or mind demands stillness after struggle. Take the retreat. The battle isn't over, but you cannot fight from an empty vessel.",
        "Reversed, you refuse to rest and pay for it, or the retreat has stretched into hiding.",
        "A knight lies in effigy on a tomb inside a chapel. Three swords hang above him on the wall; a fourth lies beneath him. A stained glass window depicts a figure blessing a supplicant.",
        "The chapel-effigy is death of the self that fought — a symbolic death of exhaustion. The three swords hung on the wall are conflicts set down; the fourth beneath supports him. The stained glass promises blessing awaits when the seeker rises."),
    (5, "Five of Swords",
        ["conflict", "hollow victory", "loss", "defeat", "pyrrhic win"],
        ["reconciliation", "moving past conflict", "amends", "release of resentment", "compromise"],
        "Five of Swords is a win nobody wanted. You may have taken the field, but at what cost? Reassess whether the fight was worth the friends now walking away.",
        "Reversed, reconciliation becomes possible. Amends made, pride set down, or a slow letting-go of a grudge you didn't know you were nursing.",
        "A smug figure holds three swords and picks up more from the ground while two defeated figures walk away hunched. A storm-clouded sky darkens the scene.",
        "The victor's smirk is the whole card's teaching — he won an argument and lost people. The defeated walk with backs turned, refusing further engagement. The storm sky shows this 'victory' unsettled the atmosphere itself."),
    (6, "Six of Swords",
        ["passage", "transition", "moving away from pain", "gradual healing", "leaving trouble behind"],
        ["stuck in the past", "unable to move on", "returning to trouble", "delayed passage", "resistance to change"],
        "Six of Swords ferries you from rough water to calm — leaving something behind, not with joy but with quiet necessity. The passage is slow. Trust the ferryman.",
        "Reversed, you can't quite make the crossing. Ties to the shore behind hold you; or the boat turns and drifts back.",
        "A ferryman poles a small boat carrying a cloaked figure and a child across flat water. Six swords stand upright in the boat's floor.",
        "The upright swords carried in the boat are the mental burdens still with the traveler — they cross but are not left. The flat water contrasts with the choppy water on one side, showing the direction of relief."),
    (7, "Seven of Swords",
        ["stealth", "strategy", "deception", "getting away with it", "cunning"],
        ["confession", "return of stolen goods", "caught out", "coming clean", "reversed deception"],
        "Seven of Swords is the sneak — sometimes you, sometimes done to you. Strategic withdrawal or petty theft, depending on the reader. Watch your inner motive; watch others' actions.",
        "Reversed, the deception surfaces. Confession, exposure, or the returned realization that shortcuts cost more than they saved.",
        "A figure tiptoes away from a distant colorful encampment, carrying five swords, leaving two behind. He glances back with a wry expression.",
        "The two swords left behind are the giveaway — the thief could not carry it all, and evidence remains. His wry glance shows self-awareness — he knows this may catch up. The distant camp is the community he skirts rather than confronts."),
    (8, "Eight of Swords",
        ["restriction", "self-imposed limits", "victim mindset", "feeling trapped", "powerlessness"],
        ["release", "self-empowerment", "new perspective", "freedom claimed", "insight into the trap"],
        "Eight of Swords is a self-made cage — bound and blindfolded by eight upright swords, but the ties are loose and the way out is clear if she looks. The prison is mental.",
        "Reversed, the blindfold comes off. Recognizing that the cage was never locked; the door was never barred.",
        "A blindfolded, loosely bound woman stands in mud surrounded by eight swords planted in a partial ring. A distant castle rises behind her.",
        "The partial ring of swords has an opening — she is not surrounded, only surrounded on the side she faces. The muddy ground shows that stuckness feels heavy; but her hands, though tied, could easily slip free."),
    (9, "Nine of Swords",
        ["anxiety", "nightmares", "worry spiral", "guilt", "insomnia of the mind"],
        ["relief", "seeking help", "confronting fears", "recovery from anxiety", "hope returning"],
        "Nine of Swords is the 3 a.m. mind — sitting up in bed with worry as an unwanted guest. Most of what haunts here is fear projected past reality. Turn on a light; call someone.",
        "Reversed, dawn breaks. Anxieties recede, help is asked for and received, or you find the fear was smaller than it looked in the dark.",
        "A figure sits up in bed, face buried in hands. Nine swords hang on the wall behind. The bedspread is patterned with roses and astrological symbols.",
        "The nine swords behind (not touching her) are the fears in her mind — hanging in the air, not embodied. The roses and astrological symbols on the bedspread show that beauty and cosmic order continue beneath the panic — reality has not actually broken."),
    (10, "Ten of Swords",
        ["endings", "rock bottom", "betrayal", "collapse", "the worst is over"],
        ["recovery", "surviving the crisis", "hard-won lessons", "prolonged suffering", "dawn breaking"],
        "Ten of Swords is the worst that could happen — and having happened, is over. The sun rises at the horizon; there is no more damage this can do. Begin again from the truth.",
        "Reversed, either recovery is genuinely underway, or you keep the ten blades in place by refusing to let the ending complete.",
        "A figure lies face-down on the ground, pierced by ten swords in the back. A red cloak covers his lower body. Behind him, the sun rises over dark water.",
        "The excessive number of blades makes the wound almost theatrical — this is symbolic death, not literal. The rising sun on the horizon is the card's real message: the light is already returning at the moment of worst darkness."),
    (11, "Page of Swords",
        ["curiosity", "sharp intellect", "vigilance", "new ideas", "quick learning"],
        ["gossip", "restlessness", "harsh words", "immature judgement", "mental scattering"],
        "Page of Swords is the eager thinker — asking hard questions, spotting inconsistencies, learning fast. Curiosity paired with sharpness; watch the tongue.",
        "Reversed, curiosity turns to gossip. Judgement forms before understanding; sharpness cuts unnecessarily.",
        "A youthful figure stands on a windy hilltop holding a sword aloft with both hands. Clouds churn behind him; birds fly in the distance.",
        "The two-handed grip shows a mind still learning to wield sharpness with control. The windy hilltop is the exposed position of one who thinks in public — vulnerable to counter-thought. The distant birds are new ideas approaching from beyond."),
    (12, "Knight of Swords",
        ["fast action", "focused drive", "intellectual courage", "direct communication", "ambition"],
        ["recklessness", "impulsive words", "aggression", "burnout", "rushing without planning"],
        "Knight of Swords charges straight at the truth — no diplomacy, no delay. Bold in mind and speech; brilliant at cutting through nonsense; sometimes tone-deaf to consequences. Speak — but check the aftermath.",
        "Reversed, the charge becomes reckless. Impulsive words, rushed judgements, or intellectual arrogance that alienates allies.",
        "A knight in full armor charges forward on a leaping white horse, sword raised high. His cape billows; the sky is stormy.",
        "The leaping horse shows momentum ahead of ground — thought moving faster than context allows. The billowing cape and stormy sky show the turbulence such speed generates; his raised sword is intellect leading the whole body of action."),
    (13, "Queen of Swords",
        ["clear-eyed wisdom", "honesty", "independence", "sharp discernment", "unsentimental grace"],
        ["coldness", "harsh judgement", "bitterness", "isolation", "loneliness"],
        "Queen of Swords sees clearly and speaks the truth without cruelty. She has been through grief and does not flinch from what is; her boundaries are precise; her counsel priceless. Embody or seek this clarity.",
        "Reversed, clarity has hardened into coldness. Bitterness masquerades as truth; wit turns cutting; isolation is confused with strength.",
        "A crowned queen sits on a stone throne carved with butterflies and cherubs, holding an upright sword in one hand while extending the other. Clouds drift in the sky; a single bird flies overhead.",
        "The butterflies on her throne are souls transformed by loss — she has become who she is through metamorphosis. The single bird overhead is her spirit ally; her extended hand is offered wisdom without demand."),
    (14, "King of Swords",
        ["clear-headed authority", "ethical rule", "intellectual mastery", "impartial judgement", "truth-based leadership"],
        ["tyranny of logic", "coldness", "manipulation via facts", "cruel judgement", "rigid rules"],
        "King of Swords rules by truth and principle — no favoritism, no theatrics, no shortcuts. His judgement is trusted because it's consistent. Consult the highest reason available to you.",
        "Reversed, authority calcifies into rigidity. Logic used as a weapon; principles applied without mercy; facts weaponized to control.",
        "A crowned king sits on a stone throne with butterflies and crescent moons, holding an upright sword tilted slightly to the right. Blue robes flow from his shoulders.",
        "The slight tilt of the sword is his humanity — pure vertical would be inhuman law; his ruling has one degree of mercy built in. Butterflies and crescents connect him to the Queen (transformation and intuition) — his logic includes what she taught him."),
]

_PENTACLES = [
    (1, "Ace of Pentacles",
        ["new opportunity", "prosperity", "manifestation", "abundance seed", "material beginning"],
        ["missed opportunity", "delayed prosperity", "poor planning", "greed", "materialism as escape"],
        "Ace of Pentacles is the seed of tangible good — a job offer, an inheritance, a real-world opportunity being placed in your hand. Accept it and plant it well.",
        "Reversed, the seed drops. Opportunity missed, or hands too greedy to plant it correctly.",
        "A hand from a cloud holds a large golden pentacle above a lush garden. A path leads through an archway of flowers toward distant mountains.",
        "The flower-arch path is the well-tended future available to whoever plants this seed with care. The mountains beyond are long-term stability earned. The pentacle held out is grace made material — earth's version of the Ace of Cups."),
    (2, "Two of Pentacles",
        ["juggling", "adaptability", "prioritization", "balance", "flexibility"],
        ["overwhelm", "dropped priorities", "poor time management", "chaos", "unable to balance"],
        "Two of Pentacles is the juggler — balancing money, time, and commitments with rhythm. It's possible, but only with movement. Stop dancing and both balls fall.",
        "Reversed, the juggle collapses. Too much taken on; priorities dropped; overwhelm freezing all motion.",
        "A figure in a tall hat juggles two coins linked by a green infinity loop while dancing at the edge of the sea. Ships ride wild waves behind him.",
        "The infinity loop between the coins shows that balance is a continuous motion, not a static state. The wild sea and ships behind are the external chaos he manages while dancing — the trick is not stillness but rhythm."),
    (3, "Three of Pentacles",
        ["collaboration", "craftsmanship", "learning through work", "teamwork", "mastery in progress"],
        ["lack of teamwork", "disharmony", "amateur work", "isolated effort", "cut corners"],
        "Three of Pentacles is skilled hands working together — each contributes something the others cannot. Apprenticeship, collaboration, the joy of making something bigger than you.",
        "Reversed, teamwork breaks down. Egos compete; corners get cut; the craftsman works alone when they shouldn't.",
        "A stonemason works on a cathedral archway, standing on a bench. A monk and a nobleman consult from an architectural plan nearby.",
        "Three trades unite: craft (mason), spirit (monk), and resources (nobleman). No cathedral is built alone. The archway being built is the passage collaboration makes possible — sacred spaces require plural hands."),
    (4, "Four of Pentacles",
        ["security", "holding on", "conservation", "financial prudence", "attachment to control"],
        ["generosity", "letting go", "financial insecurity", "reckless spending", "release of grip"],
        "Four of Pentacles holds tight — sensible savings turned to clenching. Financial control has its place, but a life gripped this hard cannot receive what tries to arrive. Loosen a finger.",
        "Reversed, either healthy release begins (generosity returns) or grip fails entirely (spending gets reckless).",
        "A crowned figure sits on a stone block clutching one pentacle to his chest, one on his crown, and two beneath his feet.",
        "The four pentacles represent complete material control — head (thoughts), heart (emotions), and feet (ground) all covered. Nothing enters, nothing leaves — the arithmetic of hoarding. The stone block seat outside a city reveals isolation as the cost."),
    (5, "Five of Pentacles",
        ["material loss", "hardship", "isolation", "financial worry", "feeling excluded"],
        ["recovery", "asking for help", "return of security", "spiritual richness in hardship", "end of hard times"],
        "Five of Pentacles is a hard patch — money short, warmth outside somebody else's window. But the church behind the beggars is available; help exists if pride can walk in.",
        "Reversed, recovery begins. Asking for help finally happens; the door opens; hardship eases.",
        "Two poor figures — one on crutches — trudge through snow past a stained-glass church window. The window glows warmly, but they don't look up.",
        "The lit church window right behind them is the missed help — refuge exists but pride, shame, or focus on the ground keeps them from seeing it. The five pentacles on the window are the very abundance they walk past."),
    (6, "Six of Pentacles",
        ["generosity", "giving and receiving", "sharing wealth", "charity", "fair exchange"],
        ["strings attached", "power imbalance", "debt", "one-sided giving", "unfair exchange"],
        "Six of Pentacles is the flow of resources — money, time, help — moving between those who have and those who need. Give freely; receive with dignity.",
        "Reversed, the flow is distorted. Charity with strings attached, debts held over heads, one-sided giving that entrenches inequality.",
        "A wealthy figure weighs coins in a scale while dropping money into the hands of two kneeling supplicants.",
        "The scales in one hand and coins flowing from the other unite justice and generosity — this is measured giving, not thoughtless. But the kneeling posture of the receivers hints at the reversed reading: power imbalance sits inside every act of charity."),
    (7, "Seven of Pentacles",
        ["patience", "long-term investment", "assessment", "harvest waiting", "sustained effort"],
        ["impatience", "wasted effort", "poor planning", "hasty judgement", "abandoning near payoff"],
        "Seven of Pentacles is the pause to look at what you've grown so far — leaning on the hoe, checking whether the tending is producing fruit. Trust the season; the harvest is close but not now.",
        "Reversed, impatience wastes what patience would have finished. Or effort was misdirected and you're only now realizing.",
        "A weary farmer leans on a hoe, gazing at a vine heavy with seven pentacles. Green leaves fill the field around him.",
        "The leaning posture is the moment between work and harvest — earned pause. The fully-formed pentacles on the vine are visible reward not yet plucked; the ripe timing is the whole card's teaching. Effort has done what it can; nature completes it."),
    (8, "Eight of Pentacles",
        ["apprenticeship", "diligence", "skill-building", "mastery through practice", "focused work"],
        ["perfectionism", "monotony", "shortcut mentality", "lack of ambition", "boredom"],
        "Eight of Pentacles is the apprentice at the bench — repeating the craft until the hands know it without asking. Mastery is built one pentacle at a time. Show up again.",
        "Reversed, dedication turns to perfectionism or the repetition becomes monotony without growth. Or the shortcut mentality tries to skip the hours craft requires.",
        "A craftsman hammers on a pentacle at a workbench, six finished pentacles already displayed on a post. A distant town suggests separation from the world.",
        "The distance from the town is deliberate — deep skill requires solitude. The six finished coins on display are proof of practice; the one in progress is present focus; the seventh is at his feet, marking that work is ongoing, not final."),
    (9, "Nine of Pentacles",
        ["self-sufficiency", "abundance", "solitary success", "refinement", "earned luxury"],
        ["overwork", "lack of self-worth", "financial dependence", "shallow luxury", "isolation in success"],
        "Nine of Pentacles is the reward of long solo work — your own garden, your own means, your own peace. You built this. Enjoy the vines without needing anyone's permission.",
        "Reversed, self-sufficiency curdles into isolation, or wealth was gained by living too small.",
        "A wealthy woman in a lavish gown stands in her vineyard, a hooded falcon on her gloved hand. Nine pentacles grow among the vines; a snail crawls at her feet.",
        "The hooded falcon is her wild nature — powerful, but she is its keeper. The snail is the slowness of true wealth — this abundance was not overnight. The nine pentacles among vines are earnings woven into the very life she's built."),
    (10, "Ten of Pentacles",
        ["legacy", "family wealth", "long-term security", "generational abundance", "true home"],
        ["family disputes over money", "loss of inheritance", "unstable foundations", "short-term focus", "family fracture"],
        "Ten of Pentacles is the whole estate — wealth become legacy, family become foundation, home become inheritance passed to the next generation. Multi-generational thriving.",
        "Reversed, the legacy cracks. Family disputes over money, lost inheritance, or shortsighted decisions that unwind what took generations to build.",
        "An elderly figure sits under an archway in a courtyard, surrounded by family across three generations and two dogs. Ten pentacles float in an arrangement over the scene.",
        "The three generations — elder, adults, child — mark true legacy: wealth that spans time. The dogs signal loyalty across generations; the archway is the passage each generation traverses. The ten pentacles form the Tree of Life pattern — complete, sacred wealth."),
    (11, "Page of Pentacles",
        ["studious start", "new venture", "practical curiosity", "opportunity to learn", "diligent focus"],
        ["distraction", "procrastination", "lack of follow-through", "unrealistic goals", "immature planning"],
        "Page of Pentacles is the earnest student — a new job, a new course, a new practical skill approached with reverence. Head down, willing to learn slowly. This is the beginning of mastery.",
        "Reversed, focus scatters. Procrastination, unrealistic ambitions, or a plan proposed with no work put in.",
        "A young figure stands in a lush field, gazing intently at a pentacle held up in both hands. Distant mountains and freshly-tilled earth are behind.",
        "The two-handed reverent hold is the apprentice mindset — the pentacle is precious because the seeker knows nothing yet. The tilled earth is preparation for growth; the mountains are long-term destination made visible before departure."),
    (12, "Knight of Pentacles",
        ["reliability", "methodical work", "patience", "responsibility", "steadfast pace"],
        ["stagnation", "boredom", "over-caution", "workaholism", "stubbornness"],
        "Knight of Pentacles is the plodding, unglamorous, endlessly reliable one. He doesn't gallop — he plows. Systems, routines, showing up. This slow style wins over decades.",
        "Reversed, reliability turns to inflexibility. Boredom, stagnation, refusal to change even when the field is depleted, or workaholism dressed as duty.",
        "A knight sits still on a stationary heavy black horse in a plowed field, holding a single pentacle. His armor is decorated with leaves.",
        "The stationary horse is the whole card — this knight is defined by NOT charging. The plowed field around him is what such patience produces. The leaves on armor mark him as of earth, not fire — sustaining, not sparking."),
    (13, "Queen of Pentacles",
        ["nurturing abundance", "practical wisdom", "grounded warmth", "resourcefulness", "domestic mastery"],
        ["overwork", "smothering care", "material obsession", "neglect of self", "financial dependence"],
        "Queen of Pentacles turns any space into a home — resourceful, warm, deeply competent at the physical world. She feeds you, tends the garden, runs the household as a small kingdom. Embody this practical grace.",
        "Reversed, her nurture turns to overwork or possessive care. She loses herself in the tending, or becomes obsessed with material things as substitutes for warmth.",
        "A crowned queen sits on a garden throne carved with cherubs and goats, holding a pentacle in her lap. A rabbit hops nearby; flowers and lush vegetation surround her.",
        "The rabbit is fertility and quiet abundance; the goats on the throne are Capricorn's steadfast climb; the flowers are the ornament that follows real tending. Her pentacle rests on her lap — she is at home with material reality, not gripping it."),
    (14, "King of Pentacles",
        ["prosperity", "abundance mastered", "business acumen", "reliable provider", "material success"],
        ["greed", "corruption", "stubbornness", "materialism", "controlling with wealth"],
        "King of Pentacles has built the whole estate — money, property, business, legacy. Not flashy; deeply rooted. He gives generously because he has enough. Consult or embody this stable provider.",
        "Reversed, wealth becomes his prison. Greed, corruption, using money to control people, or treating everything (including relationships) as transactions.",
        "A crowned king sits on a throne carved with bulls, holding a scepter and a large pentacle. Grapevines drape over the throne; a castle stands in the background.",
        "The bulls on the throne are Taurus — patient, unshakeable material stability. The grapevines are earned pleasure and continuous fruit. The castle behind is his built enterprise — no accident, no inheritance alone; his own construction."),
]


def build_seed_entries():
    """Return a list of card dicts ready to be appended to SEED_CARDS."""
    entries = []
    ordered = [("Wands", _WANDS), ("Cups", _CUPS), ("Swords", _SWORDS), ("Pentacles", _PENTACLES)]
    for suit, cards in ordered:
        meta = SUIT_META[suit]
        for (num, name, kw_up, kw_rev, upright, reversed_, desc, symb) in cards:
            fname_num = f"{num:02d}"
            filename = f"{meta['file']}{fname_num}.jpg"
            entries.append({
                "name": name,
                "number": num,
                "arcana": "Minor",
                "suit": suit,
                "element": meta["element"],
                "image_emoji": meta["emoji"],
                # Full URL via Special:FilePath (follows redirect to actual upload URL)
                "image_url": f"https://commons.wikimedia.org/wiki/Special:FilePath/{filename}",
                "keywords_upright": kw_up,
                "keywords_reversed": kw_rev,
                "upright_meaning": upright,
                "reversed_meaning": reversed_,
                "description": desc,
                "symbolism": symb,
                "_filename": filename,   # used to build WIKI_SOURCES entry
                "_slug": f"{suit.lower()}-{fname_num}.jpg",
            })
    return entries
